#ifndef TRANSITMAP_TEST_DROPOVERLAPPINGSTATIONSTEST_H_
#define TRANSITMAP_TEST_DROPOVERLAPPINGSTATIONSTEST_H_

class DropOverlappingStationsTest {
 public:
  void run();
};

#endif  // TRANSITMAP_TEST_DROPOVERLAPPINGSTATIONSTEST_H_
