#ifndef TRANSITMAP_TEST_INNERGEOMLANEORDERTEST_H_
#define TRANSITMAP_TEST_INNERGEOMLANEORDERTEST_H_

class InnerGeomLaneOrderTest {
 public:
  void run();
};

#endif  // TRANSITMAP_TEST_INNERGEOMLANEORDERTEST_H_
