#ifndef TRANSITMAP_TEST_LANDMARKDISPLACEMENTTEST_H_
#define TRANSITMAP_TEST_LANDMARKDISPLACEMENTTEST_H_

class LandmarkDisplacementTest {
 public:
  void run();
};

#endif  // TRANSITMAP_TEST_LANDMARKDISPLACEMENTTEST_H_

