#ifndef TRANSITMAP_TEST_MEHIGHLIGHTDISPLACEMENTTEST_H_
#define TRANSITMAP_TEST_MEHIGHLIGHTDISPLACEMENTTEST_H_

class MeHighlightDisplacementTest {
 public:
  void run();
};

#endif  // TRANSITMAP_TEST_MEHIGHLIGHTDISPLACEMENTTEST_H_
