#ifndef TRANSITMAP_TEST_STATIONLABELOPTIMIZERTEST_H_
#define TRANSITMAP_TEST_STATIONLABELOPTIMIZERTEST_H_

class StationLabelOptimizerTest {
 public:
  void run();
};

#endif  // TRANSITMAP_TEST_STATIONLABELOPTIMIZERTEST_H_
