#ifndef TRANSITMAP_TEST_TERMINUSLABELPLACEMENTTEST_H_
#define TRANSITMAP_TEST_TERMINUSLABELPLACEMENTTEST_H_

class TerminusLabelPlacementTest {
public:
  void run();
};

#endif  // TRANSITMAP_TEST_TERMINUSLABELPLACEMENTTEST_H_

